### ISSUE TITLE
too much memory is required for hign levels of compressions

### ISSUE THREAD

**Issue by okbob** [adjust/pg_cryogen#2]
I tested insert 1M rows 
<pre>
create table test(a int);
create table test2 (like test) using pg_cryogen;
insert into test select random()*100000 from generate_series(1,1000000);
</pre>
with 
<pre>
set pg_cryogen.zstd_compression_level=22;
</pre>
the statement
<pre>
insert into test2 select * from test;
</pre>
requires about 4GB RAM (original table has 35MB, compressed table has 27MB).

**Comment by zilder** [comment]
Hi @okbob,

Thanks for the report! I run a quick test and can see that might be an issue with low levels of compression too:

* pg_cryogen.zstd_compression_level=22:
![plot](https://user-images.githubusercontent.com/1409693/80705038-fa515700-8ae5-11ea-909f-2d95b4cc623a.png)

* pg_cryogen.zstd_compression_level=0:
![plot_compression0](https://user-images.githubusercontent.com/1409693/80705102-1b19ac80-8ae6-11ea-8bac-cc89af23a9e9.png)

I'll investigate it.

**Comment by zilder** [comment]
Fixed memory leaks. I guess I was relying on automatic memory context purge on each iteration which as it turned out isn't there. Anyway after explicit memory deallocation things seem to improve. Thanks again for pointing this out!
![plot_memcxt2](https://user-images.githubusercontent.com/1409693/80737106-54b4dc80-8b13-11ea-89d5-d5255ddb58f4.png)

**Comment by zilder** [comment]
One thing i think i should clarify is why so much memory was allocated in the first place when the entire dataset is about 35Mb. Two reasons:

* `pg_cryogen` uses internally 1 Mb blocks. They gets compressed and split into 8Kb pages. All tuples in the 1Mb block get the same blockno (even though they could physically be spread over several pages). To use bitmap index scans it is important that for each blockno there are no more than `MaxHeapTuplesPerPage` `ItemId`s (about 290). When 1Mb block is filled with this number of tuples of just one int4 field it's almost empty but it has to be flushed to disk.

* when `zstd` or `lz4` estimate the buffer size for compressed data they are very conservative and require buffer actually larger than original data. E.g. for 1Mb block `zstd` asked for 1.004Mb buffer (the actual size after compression was about 1700-1800 bytes on average for this test). Since those almost empty blocks weren't deallocated until the end of query we got so much memory hanging.

1 million records / 290 * 1Mb ≈ 3.5 Gb

**Comment by okbob** [comment]
It is fixed, thank you
